In [1]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.11/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.11/dist-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2025.7.14)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.4.2)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from kaggle) (5.29.5)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.11/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.11/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from kaggle) (0.5.1)

In [2]:
import os
import json

from zipfile import ZipFile
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

Kaggle and Dataset

In [3]:
kaggle_dictionary = json.load(open("/content/kaggle.json"))

In [4]:
kaggle_dictionary.keys()

dict_keys(['username', 'key'])

In [5]:
# setup kaggle credentials as environment variables
os.environ["KAGGLE_USERNAME"] = kaggle_dictionary["username"]
os.environ["KAGGLE_KEY"] = kaggle_dictionary["key"]

In [6]:
!kaggle datasets download -d lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

Dataset URL: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews
License(s): other
Downloading imdb-dataset-of-50k-movie-reviews.zip to /content
  0% 0.00/25.7M [00:00<?, ?B/s]
100% 25.7M/25.7M [00:00<00:00, 1.38GB/s]

In [7]:
!ls

imdb-dataset-of-50k-movie-reviews.zip  kaggle.json  sample_data

In [8]:
# unzip the dataset file
with ZipFile("imdb-dataset-of-50k-movie-reviews.zip", "r") as zip_ref:
  zip_ref.extractall()

In [9]:
data = pd.read_csv("/content/IMDB Dataset.csv")

In [10]:
data.shape

(50000, 2)

In [12]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [13]:
data["sentiment"].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [14]:
data.replace({"sentiment": {"positive": 1, "negative": 0}}, inplace=True)

/tmp/ipython-input-2568826810.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace({"sentiment": {"positive": 1, "negative": 0}}, inplace=True)

In [15]:
data.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [16]:
data["sentiment"].value_counts()

sentiment
1    25000
0    25000
Name: count, dtype: int64

Train and Test

In [17]:
# split data into training data and test data
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

In [18]:
print(train_data.shape)
print(test_data.shape)

(40000, 2)
(10000, 2)

Data Processing
- Tokenize
- Can use spacy for lemitization regex etc

In [19]:
# Tokenize text data
# Here 5000 words vocabularly from training data
# entire sentecnce -> index provide kar rahe
tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(train_data["review"])
X_train = pad_sequences(tokenizer.texts_to_sequences(train_data["review"]), maxlen=200)
X_test = pad_sequences(tokenizer.texts_to_sequences(test_data["review"]), maxlen=200)

# "The value num_words=5000 limits the tokenizer to keep only the top 5000 most frequent unique words when creating the word index for training."
# Pads or truncates each sequence to a length of exactly 200:
# jyada words hai each sentence unko truncate to 200

# Tokenizer -> pad Sequence [200] dimension convert each sentence

In [24]:
len(X_train)

40000

Input shape is 200 for each review
Converted sentence to 200D vector kind of

In [21]:
len(X_train[0])

200

In [23]:
Y_train = train_data["sentiment"]
Y_test = test_data["sentiment"]

# LSTM - Long Short-Term Memory : Word Embedding ke saath use
- After Word Embedding vector LSTM use for more accuracy
- Sequence data set: input text linked to previous text
- Time series data


- input_dim=5000 mean?
  - This is not the length of your padded input.
    - It tells the Embedding layer:
  - "There are 5000 unique possible tokens (word indices), indexed from 1 to 4999 — so build an embedding lookup table of size 5000."

### Embedding Layer
- convert each word index into (128 dimension vector)
- yeh keras embedding hap
- can use spacy and nltk etc

[45, 67, 12, ..., 0, 0]              # Shape: (200,)
↓
Embedding Layer → word vectors
↓
[[0.1, 0.7, ..., 0.3],     ← word 1 → 128-dim
 [0.05, 0.2, ..., 0.6],    ← word 2
 ...
 [0, 0, ..., 0]]           ← padding
Shape: (200, 128)
↓
LSTM processes it as a time series
↓
Output: vector → Dense → prediction

In [27]:
# build the model
# ✅ Each word embedding = a vector of 128 features
# ✅ The sentence = a time series of 200 steps
# word order = time order in the LSTM.
# [vec("I"), vec("love"), vec("this"), vec("movie")] → sequence of 128D vectors

model = Sequential()
model.add(Embedding(input_dim=5000, output_dim=128, input_length=200))
# Converts word indices to vectors
# (batch_size, 200, 128) output
# Learn to represent each word (token ID) as a 128-dimensional vector.”
#  My embedding kind of for each word which is passed to LSTM
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
# LSTM expects input of shape: (batch_size, timesteps, features)
# LSTM 200 timeseries ke tarah dekh raha
# Processes word vectors sequentially, remembers context
model.add(Dense(1, activation="sigmoid"))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

LSTM Apna internally word order ke hisab se RNN use kar raha to train and predict, I know the theoritical part
Also I know embedding karne ke kafi tarike hai word -> vectors
here use model Embedding jaise bhi do

In [28]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
# compile the model
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [31]:
model.fit(X_train, Y_train, epochs=1, batch_size=64, validation_split=0.2)

500/500 ━━━━━━━━━━━━━━━━━━━━ 190s 380ms/step - accuracy: 0.8104 - loss: 0.4250 - val_accuracy: 0.7896 - val_loss: 0.4410

In [32]:
loss, accuracy = model.evaluate(X_test, Y_test)
print(f"Test Loss: {loss}")
print(f"Test Accuracy: {accuracy}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 37s 115ms/step - accuracy: 0.7850 - loss: 0.4419
Test Loss: 0.44235658645629883
Test Accuracy: 0.7860999703407288

Building a Predictive System

In [33]:
def predict_sentiment(review):
  # tokenize and pad the review
  sequence = tokenizer.texts_to_sequences([review])
  padded_sequence = pad_sequences(sequence, maxlen=200)
  prediction = model.predict(padded_sequence)
  sentiment = "positive" if prediction[0][0] > 0.5 else "negative"
  return sentiment

In [34]:
# example usage
new_review = "This movie was fantastic. I loved it."
sentiment = predict_sentiment(new_review)
print(f"The sentiment of the review is: {sentiment}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 456ms/step
The sentiment of the review is: positive